import 'package:ecommerce/models/product.dart';
class MyProducts {
  static List<Product> todosProdutos = [
    ...MyProducts.gamer,
    ...MyProducts.hardware,
    ...MyProducts.network,
  ];
  static List<Product> gamer = [
    Product(
      id: 1,
      name: 'Controle com fio gamer',
      price: 65.60,
      image: 'assets/gamer/controlecomfio.jpg',
      description: 'Controle com fio para Xbox 360',
      quantity: 1,
    ),
    Product(
      id: 2,
      name: 'Controle com fio gamer',
      price: 287.00,
      image: 'assets/gamer/controlecomfio1.jpg',
      description: 'Controle com fio para Nintendo Switch',
      quantity: 1,
    ),
    Product(
      id: 3,
      name: 'Controle com fio gamer',
      price: 164.00,
      image: 'assets/gamer/controlecomfio2.jpg',
      description: 'Controle com gio gamer, controlador P/ Nsw Wired Lightning',
      quantity: 1,
    ),
    Product(
      id: 4,
      name: 'Mouse para gamer',
      price: 23.00,
      image: 'assets/gamer/mousegamer.jpg',
      description: 'Mouse para gamer, Redragon MOUSE GAMER GRIFFIN',
      quantity: 1,
    ),
    Product(
      id: 5,
      name: 'Mouse para gamer',
      price: 32.00,
      image: 'assets/gamer/mousegamer1.jpg',
      description: 'Mouse para gamer, Redragon MOUSE TITANOBOA2 M802-RGB-1',
      quantity: 1,
    ),
    Product(
      id: 6,
      name: 'Mouse para gamer',
      price: 22.00,
      image: 'assets/gamer/mousegamer2.jpg',
      description: 'Mouse para gamer, Gaming Mouse 7200 DPI Backlight Multi Color',
      quantity: 1,
    ),
    Product(
      id: 7,
      name: 'Mouse Pad',
      price: 23.00,
      image: 'assets/gamer/mousepadgamer.jpg',
      description: 'Mouse Pad Havit MP839 Gamer',
      quantity: 1,
    ),
    Product(
      id: 8,
      name: 'Mouse Pad',
      price: 32.00,
      image: 'assets/gamer/mousepadgamer1.jpg',
      description: 'Mouse Pad Gamer Iluminado led',
      quantity: 1,
    ),
    Product(
      id: 9,
      name: 'Mouse Pad',
      price: 22.40,
      image: 'assets/gamer/mousepadgamer2.jpg',
      description: 'Mousepad Gamer Speed Borda Costurada',
      quantity: 1,
    ),
    Product(
      id: 10,
      name: 'Kit teclado e mouse gamer',
      price: 68.00,
      image: 'assets/gamer/kit.jpg',
      description: 'Kit Gamer Teclado Gamer Iluminado, Mouse Gamer Com Led',
      quantity: 1,
    ),
    Product(
      id: 11,
      name: 'Kit teclado e mouse gamer',
      price: 175.00,
      image: 'assets/gamer/kit1.jpg',
      description: 'HP, Teclado e Mouse HP, GK1100, Preto, USB, ABNT 2',
      quantity: 1,
    ),
    Product(
      id: 12,
      name: 'Kit teclado e mouse gamer',
      price: 148.00,
      image: 'assets/gamer/kit2.jpg',
      description: 'Kit Teclado e Mouse Gamer Multilaser-tc195 Led',
      quantity: 1,
    ),
    Product(
      id: 13,
      name: 'Headphone gamer',
      price: 75.00,
      image: 'assets/gamer/fonedeouvidogamer.jpg',
      description: 'Headphone Fone de Ouvido Havit HV-H2232d',
      quantity: 1,
    ),
    Product(
      id: 14,
      name: 'Headphone gamer',
      price: 107.00,
      image: 'assets/gamer/fonedeouvidogamer1.jpg',
      description: 'Headphone Headset Over-Ear Gamer',
      quantity: 1,
    ),
    Product(
      id: 15,
      name: 'Headphone gamer',
      price: 114.00,
      image: 'assets/gamer/fonedeouvidogamer2.jpg',
      description: 'Headphone Kotion Gamer G2000',
      quantity: 1,
    ),
    Product(
      id: 16,
      name: 'Led para Gamer',
      price: 41.00,
      image: 'assets/gamer/ledparagamer.jpg',
      description: 'Led para Gamer, Barra de Led Rítmica Rgb',
      quantity: 1,
    ),
    Product(
      id: 17,
      name: 'Controle com fio gamer',
      price: 74.90,
      image: 'assets/gamer/ledparagamer1.jpg',
      description: 'Controle com fio gamer, Led para decoração',
      quantity: 1,
    ),
    Product(
      id: 18,
      name: 'Controle com fio gamer',
      price: 355.00,
      image: 'assets/gamer/ledparagamer2.jpg',
      description: 'Controle com fio gamer, Led Neon Zelda Sword Setup Gamer',
      quantity: 1,
    ),
  ];

  static List<Product> hardware = [
    Product(
      id: 1,
      name: "Gabinete Gamer Mancer Narok",
      price: 249.90,
      image: 'assets/hardware/gabinete_gamer.png',
      description:
          "Gabinete Gamer Mancer Narok, Rainbow, Mid-Tower, Lateral de Vidro, Com 3 Fans, Preto, MCR-NRK-RGB01",
      quantity: 1,
    ),
    Product(
      id: 2,
      name: "Gabinete Gamer BPC-C3147",
      price: 199.90,
      image: 'assets/hardware/gabinete_gamer01.jpg',
      description: "Gabinete Gamer BPC-C3147, Preto com lateral de vidro",
      quantity: 1,
    ),
    Product(
      id: 3,
      name: "Gabinete Gamer Pichau Pouter",
      price: 349.90,
      image: 'assets/hardware/gabinete_gamer02.jpg',
      description:
          "Gabinete Gamer Pichau Pouter 3 RGB Preto, com lateral de vidro, PG-P03-RGB",
      quantity: 1,
    ),
    Product(
      id: 4,
      name: "Placa de Vídeo Galax NVIDIA GeForce GTX 1660 Super",
      price: 2449.90,
      image: 'assets/hardware/placa_video.png',
      description:
          "Placa de Vídeo Galax NVIDIA GeForce GTX 1660 Super, 6GB GDDR6, 192 Bits - 60SRL7DSY91S",
      quantity: 1,
    ),
    Product(
      id: 5,
      name: "Placa de Vídeo Galax NVIDIA GeForce RTX 30 Series ",
      price: 1529.90,
      image: "assets/hardware/placa_video01.png",
      description:
          "Placa de Vídeo Galax NVIDIA GeForce RTX 30 Series, RTX 3050 35NSL8MD6YEX 8GB",
      quantity: 1,
    ),
    Product(
      id: 6,
      name: "Placa de Vídeo Quadro Nvidia T600",
      price: 1789.00,
      image: "assets/hardware/placa_video02.png",
      description: "Placa de Vídeo Quadro Nvidia T600 4GB DDR6 128Bits",
      quantity: 1,
    ),
    Product(
      id: 7,
      name: "Memória Desktop Crucial Basics",
      price: 119.90,
      image: "assets/hardware/memoria_desktop.png",
      description:
          "Memória Desktop Crucial Basics, 8GB, 2666MHz, DDR4, CL19 - CB8GU2666",
      quantity: 1,
    ),
    Product(
      id: 8,
      name: "Memória Desktop Kingston Fury Beast",
      price: 289.90,
      image: "assets/hardware/memoria_desktop01.png",
      description:
          "Memória Desktop Kingston Fury Beast, 16GB, 3200MHz, DDR4, CL16 - KF432C16BB1/16",
      quantity: 1,
    ),
    Product(
      id: 9,
      name: "Memória Desktop Oxy Gamer",
      price: 379.90,
      image: "assets/hardware/memoria_desktop02.png",
      description:
          "Memoria Desktop Oxy Gamer, 8GB, 3200MHz, DDR4, CL22 - OXYGAMER32N22S8/8",
      quantity: 1,
    ),
    Product(
      id: 10,
      name: "SSD Externo Portátil Sandisk Extreme 1TB",
      price: 669.90,
      image: "assets/hardware/ssd_externo.png",
      description: "SSD Externo Portátil Sandisk Extreme 1TB, SDSSDE60-1T00-G2",
      quantity: 1,
    ),
    Product(
      id: 11,
      name: "SSD Externo Portátil Kingston, 2TB",
      price: 1099.90,
      image: "assets/hardware/ssd_externo01.png",
      description: "SSD Externo Portátil Kingston, 2TB, XS2000",
      quantity: 1,
    ),
    Product(
      id: 12,
      name: "SSD Externo Portátil Sandisk Extreme 2TB",
      price: 939.90,
      image: "assets/hardware/ssd_externo02.png",
      description:
          "SSD Externo Portátil Sandisk Extreme 2TB, SDSSDE61-2T00-G25",
      quantity: 1,
    ),
    Product(
      id: 13,
      name: "Cooler para Processador - Master Hyper, LED, Turbo White",
      price: 219.90,
      image: "assets/hardware/cooler_processador.png",
      description:
          "Cooler para Processador Cooler Master Hyper 212 LED Turbo White Edition, LED, AMD/Intel - RR-212TW-16PW-R1",
      quantity: 1,
    ),
    Product(
      id: 14,
      name: "Cooler para Processador - Master Hyper",
      price: 149.90,
      image: "assets/hardware/cooler_processador01.jpg",
      description:
          "Cooler para Processador Cooler Master AMD/ Intel Hyper H412R - RR-H412-20PK-R2",
      quantity: 1,
    ),
    Product(
      id: 15,
      name: "Cooler para Processador - Master Hyper, Black Edition",
      price: 319.90,
      image: "assets/hardware/cooler_processador02.jpg",
      description:
          "Cooler para Processador Cooler Master Hyper 212 Black Edition, LGA 1700, Intel e AMD, 120mm, Preto - RR-212S-20PK-R2",
      quantity: 1,
    ),
    Product(
      id: 16,
      name: "Placa Mãe Asus",
      price: 1319.90,
      image: "assets/hardware/placa_mae.jpg",
      description: "Placa Mãe Asus TUF B360M-PLUS Gaming/BR",
      quantity: 1,
    ),
    Product(
      id: 17,
      name: "Placa Mãe Intel H310",
      price: 649.90,
      image: "assets/hardware/placa_mae01.jpg",
      description: "Placa Mãe Intel, Intel H310, LGA 1151, DDR4",
      quantity: 1,
    ),
    Product(
      id: 18,
      name: "Placa Mãe Gigabyte B550M AORUS Elite",
      price: 739.90,
      image: "assets/hardware/placa_mae02.jpg",
      description:
          "Placa Mãe Gigabyte B550M AORUS Elite, Chipset B550, AMD AM4, mATX, DDR4",
      quantity: 1,
    ),
  ];
  static List<Product> network = [
      Product(
      id: 1,
      name: 'Roteador Mikrotik Hex',
      price: 439.00,
      image: 'assets/network/mikrotik.jpeg',
      description: 'Roteador Mikrotik Hex Router Board RB750GR3',
      quantity: 1,
    ),
      Product(
      id: 2,
      name: 'Roteador Mikrotik Routerboard',
      price: 696.00,
      image: 'assets/network/mikrotik01.jpeg',
      description: 'Roteador Mikrotik Rb450g Routerboard3',
      quantity: 1,
    ),
      Product(
      id: 3,
      name: 'Roteador Mikrotik Access Point',
      price: 209.00,
      image: 'assets/network/mikrotik02.jpeg',
      description: 'Roteador Mikrotik Access Point - Mikrotik RB941-2n',
      quantity: 1,
    ),
      Product(
      id: 4,
      name: 'Adaptador Wireless Syang Mini',
      price: 24.90,
      image: 'assets/network/mini.jpeg',
      description: 'Mini Adaptador Wifi Nano 2.4 Ghz, Syang',
      quantity: 1,
    ),
      Product(
      id: 5,
      name: 'Adaptador Wireless TP-Link Dual-Band',
      price: 149.50,
      image: 'assets/network/mini01.jpeg',
      description: 'Adaptador USB wireless dual band',
      quantity: 1,
    ),
      Product(
      id: 6,
      name: 'Adaptador Wireless TP-Link 300MBPS',
      price: 68.90,
      image: 'assets/network/mini02.jpeg',
      description: 'Adaptador USB Wireless N 300Mbps, TP-Link, TL-WN821NS',
      quantity: 1,
    ),
      Product(
      id: 7,
      name: 'D-Link Repetidor Wireless',
      price: 149.80,
      image: 'assets/network/repetidor.jpeg',
      description: 'D-Link Repetidor Wireless',
      quantity: 1,
    ),
      Product(
      id: 8,
      name: 'Repetidor Wireless Homesen 300M',
      price: 62.00,
      image: 'assets/network/repetidor01.jpeg',
      description: 'Homesen Amplif sinal WiFi 300M',
      quantity: 1,
    ),
      Product(
      id: 9,
      name: 'Repetidor Wireless TP-Link 300Mbps',
      price: 123.40,
      image: 'assets/network/repetidor02.jpeg',
      description: 'Repetidor TP-Link Wire 300Mbps',
      quantity: 1,
    ),
      Product(
      id: 10,
      name: 'Switch TP-Link 8 Portas',
      price: 360.30,
      image: 'assets/network/switch.jpeg',
      description: 'TP-Link TL-SG108 Switch Ggbit 8 Portas',
      quantity: 1,
    ),
      Product(
      id: 11,
      name: 'Switch TP-Link 5 Portas',
      price: 85.40,
      image: 'assets/network/switch01.jpeg',
      description: 'Switch TP-Link 5 Portas TL',
      quantity: 1,
    ),
      Product(
      id: 12,
      name: 'Switch TP-Link 8 Portas',
      price: 768.90,
      image: 'assets/network/switch02.jpeg',
      description: 'Switch TP-Link 8 Portas, Gigabit, 2 Portas SFP TL-SG3210',
      quantity: 1,
    ),
      Product(
      id: 13,
      name: 'Expansor HUB USB',
      price: 28.00,
      image: 'assets/network/usb.jpeg',
      description: 'Extensões Mini Hub USB, Expansor',
      quantity: 1,
    ),
      Product(
      id: 14,
      name: 'Expansor HUB USB 7 Portas',
      price: 29.90,
      image: 'assets/network/usb01.jpeg',
      description: 'Hub Usb 7 Portas 2.0 Hd Extensor',
      quantity: 1,
    ),
      Product(
      id: 15,
      name: 'Expansor HUB USB 4 Portas',
      price: 55.30,
      image: 'assets/network/usb02.jpeg',
      description: 'Expansor HUB USB, Bright, 4 PORTAS 3.0',
      quantity: 1,
    ),
  ];
}
